session BigInt_LLVM = Isabelle_LLVM + 
    directories
        "src"
        "lib"
        "src/SignedBigInteger"
    theories
        "lib/IICF_For_Loop_Add"
        "lib/IICF_More_Array"
        "src/AuxLemmas"
        "src/Setup"
        "src/WordOps"
        "src/BigInt"
        "src/Karatsuba"
        "src/BigIntSlice"
        "src/LLVM_CodeGen"
        "src/SignedBigInteger/LLVM_CodeGen"
        "src/SignedBigInteger/LLVM_CodeGen_Auxiliary"
        "src/SignedBigInteger/Basic"
        "src/SignedBigInteger/Arithmetics"
